# Generated by Django 4.0.6 on 2022-08-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='media',
        ),
        migrations.RemoveField(
            model_name='story',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ManyToManyField(blank=True, to='blog.snippetfile'),
        ),
        migrations.DeleteModel(
            name='MessageMedia',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
